# Generated by Django 4.1.5 on 2023-01-26 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='label',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 18, 20, 42, 489812, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='news',
            name='region',
            field=models.CharField(default='', max_length=200),
        ),
    ]
