# Generated by Django 4.1.5 on 2023-01-27 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_label_news_published_news_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
