# Generated by Django 4.1.5 on 2023-01-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionstatus',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regionstatus',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
